language: rust
sudo: false

# run builds for all the trains (and more)
rust:
- stable
- beta
- nightly

addons:
  apt:
    packages:
    - libcurl4-openssl-dev
    - libelf-dev
    - libdw-dev

before_script:
- |
    pip install 'travis-cargo<0.2' --user &&
    export PATH=$HOME/.local/bin:$PATH

script:
# TEMPORARY UNTIL SERDE 0.7 IS RELEASED
- |
  mkdir .travis-deps
  mkdir .cargo
  echo 'paths = ["./.travis-deps/serde"]' > .cargo/config
  git clone https://github.com/serde-rs/serde .travis-deps/serde
  pushd .travis-deps/serde
  git reset --hard origin/master
  popd
- |
    (cd hjson && travis-cargo build) &&
    (cd hjson && travis-cargo test) &&
    (cd hjson_tests && travis-cargo test -- --features with-syntex --no-default-features) &&
    (cd hjson_tests && travis-cargo --only nightly test -- features nightly-testing) &&
    (cd hjson_tests && travis-cargo --only nightly bench -- features nightly-testing) &&
    (cd hjson_tests && travis-cargo --only nightly bench -- --features "nightly-testing with-syntex" --no-default-features) &&
    (cd hjson && travis-cargo --only stable doc)

after_success:
#- (cd hjson && travis-cargo --only stable doc-upload)
#- (cd hjson_tests && travis-cargo coveralls --no-sudo)

env:
  global:
    # override the default `--features unstable` used for the nightly branch (optional)
    - TRAVIS_CARGO_NIGHTLY_FEATURE=""

    # encrypted github token for doc upload (see `GH_TOKEN` link above)
    #- secure:
