[package]
name = "serde_hjson_tests"
version = "0.1.0"
authors = ["Christian Zangl <laktak@cdak.net>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen"]
nightly-testing = ["clippy", "serde_hjson/clippy"]

[build-dependencies]
syntex = { version = "*", optional = true }
serde_codegen = { version = "*", optional = true }
skeptic = "^0.4.0"

[dependencies]
clippy = { version = "^0.*", optional = true }
num = "*"
rustc-serialize = "*"
serde = "*"
serde_hjson = { version = "*", path = "../hjson" }
serde_macros = { version = "*", optional = true }
skeptic = "^0.4.0"

[[test]]
name = "test"
path = "tests/test.rs"
