[package]
name = "serde-hjson-tests"
version = "0.1.0"
authors = ["Christian Zangl <laktak@cdak.net>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen", "quasi_codegen"]
nightly-testing = ["clippy", "serde-hjson/clippy"]

[build-dependencies]
syntex = { version = "*", optional = true }
serde_codegen = { version = "*", optional = true }
quasi_codegen = { version = "*", optional = true }
skeptic = "^0.4.0"

[dependencies]
clippy = { version = "^0.*", optional = true }
num = "^0.1.0"
rustc-serialize = "^0.3.0"
serde = "^0.7.0"
serde_json = "^0.7.0"
serde-hjson = { version = "*", path = "../hjson" }
serde_macros = { version = "^0.7.0", optional = true }
skeptic = "^0.4.0"

[[test]]
name = "test"
path = "tests/test.rs"
