[package]
name = "serde_hjson"
version = "0.1.0"
authors = ["Christian Zangl <laktak@cdak.net>", "Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
license = "MIT"
description = "A Hjson serialization file format"
repository = "https://github.com/laktak/hjson-rust"
#documentation = "https://laktak.github.io/hjson-rust/"
readme = "../README.md"
keywords = ["hjson", "json", "serde", "serialization"]

[features]
default = ["preserve_order"]
nightly-testing = ["clippy"]
preserve_order = ["linked-hash-map", "linked-hash-map/serde_impl"]

[dependencies]
serde = "^0.7.0"
#linked-hash-map = { version = "0.0.10", optional = true }
linked-hash-map = { git = "https://github.com/contain-rs/linked-hash-map.git", optional = true } # , rev = ".."
num = { version = "~0.1.27", default-features = false }
clippy = { version = "^0.*", optional = true }
